In [9]:
import numpy as np
import pandas  as pd



In [11]:
ar=np.random.rand(5)
s=pd.Series(ar,index=list("abcde"))
print(ar)
print(s)
print(type(s))
print("---")
print(s.index)
print(list(s.index))
print(s.values,type(s.values))

[0.80620165 0.59720936 0.42163518 0.85619649 0.10331788]
a    0.806202
b    0.597209
c    0.421635
d    0.856196
e    0.103318
dtype: float64
<class 'pandas.core.series.Series'>
---
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
['a', 'b', 'c', 'd', 'e']
[0.80620165 0.59720936 0.42163518 0.85619649 0.10331788] <class 'numpy.ndarray'>


In [14]:
#创建的第一种方法
dic={"a":1,"b":2,"c":3,4:5,5:6}
s=pd.Series(dic)
print(s)


a    1
b    2
c    3
4    5
5    6
dtype: int64


In [21]:
#创建的第二种方法
arr=np.random.rand(10)
s=pd.Series(arr,index=list("abcdefghij"))
print(s)

a    0.864524
b    0.419353
c    0.948061
d    0.174043
e    0.334689
f    0.286876
g    0.977706
h    0.318427
i    0.863980
j    0.562068
dtype: float64


In [23]:
#创建的第三种方法
s=pd.Series(10,index=range(7))
print(s)

0    10
1    10
2    10
3    10
4    10
5    10
6    10
dtype: int64


In [29]:
#2.2作业
dic={"Jack":90.0,"Marry":92.0,"Tom":89.0,"Zack":65.0}
s=pd.Series(dic, dtype = np.float,name="作业1")
print(s)
print("-------")

arr=np.array([90,92,89,65])
s1=pd.Series(arr,index=["Jack","Marry","Tom","Zack"], dtype = np.float,name="作业2")
print(s1)

Jack     90.0
Marry    92.0
Tom      89.0
Zack     65.0
Name: 作业1, dtype: float64
-------
Jack     90.0
Marry    92.0
Tom      89.0
Zack     65.0
Name: 作业2, dtype: float64


In [36]:
#下标索引
s=pd.Series(np.random.rand(10))
print(s)
print(s[5],type(s[6]),s[7].dtype)
print

0    0.358563
1    0.877747
2    0.316904
3    0.281655
4    0.014835
5    0.237635
6    0.571254
7    0.898193
8    0.150957
9    0.163449
dtype: float64
0.23763479315564306 <class 'numpy.float64'> float64


<function print>

In [37]:
# 标签索引
s = pd.Series(np.random.rand(5), index = ['a','b','c','d','e'])
print(s)
print(s['a'],type(s['a']),s['a'].dtype)

print(s[['a','b']])

a    0.115766
b    0.245210
c    0.624277
d    0.169583
e    0.438330
dtype: float64
0.11576617636528241 <class 'numpy.float64'> float64
a    0.115766
b    0.245210
dtype: float64


In [43]:
# 切片索引

s1 = pd.Series(np.random.rand(5))
s2 = pd.Series(np.random.rand(5), index = ['a','b','c','d','e'])
print(s1)
print(s2)
print('--------')
print(s1[1:4],s1[4])
print(s2['a':'e'],s2['c'])
print(s2[0:2],s2[3])
print('-----')


print(s2[:-1])
print(s2[::2])
# 下标索引做切片，和list写法一样

0    0.349695
1    0.871677
2    0.574680
3    0.763726
4    0.418669
dtype: float64
a    0.374094
b    0.359787
c    0.141218
d    0.299108
e    0.266246
dtype: float64
--------
1    0.871677
2    0.574680
3    0.763726
dtype: float64 0.4186690757956535
a    0.374094
b    0.359787
c    0.141218
d    0.299108
e    0.266246
dtype: float64 0.1412178639826548
a    0.374094
b    0.359787
dtype: float64 0.2991076505122501
-----
a    0.374094
b    0.359787
c    0.141218
d    0.299108
dtype: float64
a    0.374094
c    0.141218
e    0.266246
dtype: float64


In [48]:
# 布尔型索引

s = pd.Series(np.random.rand(3)*100)
#s[4] = None  # 添加一个空值
s[4]=np.nan
print(s)
bs1 = s > 50
bs2 = s.isnull()
bs3 = s.notnull()
print(bs1, type(bs1), bs1.dtype)
print(bs2, type(bs2), bs2.dtype)
print(bs3, type(bs3), bs3.dtype)
print('-----')
# 数组做判断之后，返回的是一个由布尔值组成的新的数组
# .isnull() / .notnull() 判断是否为空值 (None代表空值，NaN代表有问题的数值，两个都会识别为空值)

print(s[s > 50])
print(s[bs3])
# 布尔型索引方法：用[判断条件]表示，其中判断条件可以是 一个语句，或者是 一个布尔型数组！

0    31.334158
1    66.442707
2    10.697338
4          NaN
dtype: float64
0    False
1     True
2    False
4    False
dtype: bool <class 'pandas.core.series.Series'> bool
0    False
1    False
2    False
4     True
dtype: bool <class 'pandas.core.series.Series'> bool
0     True
1     True
2     True
4    False
dtype: bool <class 'pandas.core.series.Series'> bool
-----
1    66.442707
dtype: float64
0    31.334158
1    66.442707
2    10.697338
dtype: float64


In [53]:
#作2.3作业
s=pd.Series(np.random.rand(10)*100,index=list("abcdefghij"))
print(s)
print(s['a'],s['c'])
print(s[3:6])
print(s[s>50])

a    70.756410
b    12.148447
c    39.100535
d    86.132076
e     8.633444
f    99.110514
g    10.911665
h    71.684850
i    46.688396
j    29.458140
dtype: float64
70.75641019857868 39.10053476882437
d    86.132076
e     8.633444
f    99.110514
dtype: float64
a    70.756410
d    86.132076
f    99.110514
h    71.684850
dtype: float64


In [57]:
s=pd.Series(np.random.rand(15))
print(s.head(2))
print(s.tail())

0    0.206443
1    0.984881
dtype: float64
10    0.557912
11    0.849308
12    0.972115
13    0.593697
14    0.725560
dtype: float64


In [63]:
#重新索引reindex
s = pd.Series(np.random.rand(5),index=list("abcde"))
print(s)
s1=s.reindex(list("cdafdg"))
print(s1)
print("----")
s2 =s.reindex(list("cdafdg"),fill_value=0)
print(s2)

a    0.181434
b    0.727148
c    0.224693
d    0.281334
e    0.975332
dtype: float64
c    0.224693
d    0.281334
a    0.181434
f         NaN
d    0.281334
g         NaN
dtype: float64
----
c    0.224693
d    0.281334
a    0.181434
f    0.000000
d    0.281334
g    0.000000
dtype: float64


In [78]:
# Series对齐

s1 = pd.Series(np.random.rand(3), index = ['Jack','Marry','Tom'])
s2 = pd.Series(np.random.rand(3), index = ['Wang','Jack','Marry'])
print(s1)
print(s2)
print(s1+s2)
# Series 和 ndarray 之间的主要区别是，Series 上的操作会根据标签自动对齐
# index顺序不会影响数值计算，以标签来计算
# 空值和任何值计算结果扔为空值

Jack     0.886385
Marry    0.182280
Tom      0.441852
dtype: float64
Wang     0.030657
Jack     0.866827
Marry    0.261584
dtype: float64
Jack     1.753212
Marry    0.443863
Tom           NaN
Wang          NaN
dtype: float64


In [74]:
# 删除：.drop

s = pd.Series(np.random.rand(5), index = list('ngjur'))
print(s)
s1 = s.drop('n')
s2 = s.drop(['g','j' ])
print(s1)
print(s2)
print(s)
# drop 删除元素之后返回副本(inplace=False)

n    0.546524
g    0.207711
j    0.009831
u    0.801561
r    0.157657
dtype: float64
g    0.207711
j    0.009831
u    0.801561
r    0.157657
dtype: float64
n    0.546524
u    0.801561
r    0.157657
dtype: float64
n    0.546524
g    0.207711
j    0.009831
u    0.801561
r    0.157657
dtype: float64


In [79]:
# 添加

s1 = pd.Series(np.random.rand(5))
s2 = pd.Series(np.random.rand(5), index = list('ngjur'))
print(s1)
print(s2)
s1[5] = 100
s2['a'] = 100
print(s1)
print(s2)
print('-----')
# 直接通过下标索引/标签index添加值

s3 = s1.append(s2)
print(s3)
print(s1)
# 通过.append方法，直接添加一个数组
# .append方法生成一个新的数组，不改变之前的数组

0    0.010777
1    0.422161
2    0.984704
3    0.738102
4    0.503185
dtype: float64
n    0.923657
g    0.366401
j    0.816346
u    0.935989
r    0.043266
dtype: float64
0      0.010777
1      0.422161
2      0.984704
3      0.738102
4      0.503185
5    100.000000
dtype: float64
n      0.923657
g      0.366401
j      0.816346
u      0.935989
r      0.043266
a    100.000000
dtype: float64
-----
0      0.010777
1      0.422161
2      0.984704
3      0.738102
4      0.503185
5    100.000000
n      0.923657
g      0.366401
j      0.816346
u      0.935989
r      0.043266
a    100.000000
dtype: float64
0      0.010777
1      0.422161
2      0.984704
3      0.738102
4      0.503185
5    100.000000
dtype: float64


In [142]:
#2.4作业
s=list(range(10))
s1 = pd.Series(s,index=list('abcdefghij'),dtype=int)
print("创建s:")
print(s1)


#用的是drop
s1['a']=100
s1['f']=100
s1['g']=100
s2=s1.drop('b')
print("s修改后:")
print(s2) 
print('-------------------')

s1=pd.Series(np.random.rand(5)*10,index=list('abcde'))
s2=pd.Series(np.random.rand(5)*10,index=list('cdefg'))
print("创建s1为:")
print(s1)

print("创建s2为:")
print(s2)
s=s1+s2
print(s) 


创建s:
a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
i    8
j    9
dtype: int32
s修改后:
a    100
c      2
d      3
e      4
f    100
g    100
h      7
i      8
j      9
dtype: int32
-------------------
创建s1为:
a    0.710181
b    3.563390
c    5.134456
d    5.130547
e    0.615752
dtype: float64
创建s2为:
c    7.780418
d    6.606228
e    0.669920
f    8.235396
g    8.702857
dtype: float64
a          NaN
b          NaN
c    12.914873
d    11.736775
e     1.285672
f          NaN
g          NaN
dtype: float64


In [95]:
# Dataframe 数据结构
# Dataframe是一个表格型的数据结构，“带有标签的二维数组”。
# Dataframe带有index（行标签）和columns（列标签）

data = {'name':['Jack','Tom','Mary'],
        'age':[18,19,20],
       'gender':['m','m','w']}
frame = pd.DataFrame(data)
print(frame)  
print(type(frame))
print(frame.index,'\n1该数据类型为：',type(frame.index))
print(frame.columns,'\2该数据类型为：',type(frame.columns))
print(frame.values,'\n3该数据类型为：',type(frame.values))
# 查看数据，数据类型为dataframe
# .index查看行标签
# .columns查看列标签
# .values查看值，数据类型为ndarray

   name  age gender
0  Jack   18      m
1   Tom   19      m
2  Mary   20      w
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1) 
1该数据类型为： <class 'pandas.core.indexes.range.RangeIndex'>
Index(['name', 'age', 'gender'], dtype='object') 该数据类型为： <class 'pandas.core.indexes.base.Index'>
[['Jack' 18 'm']
 ['Tom' 19 'm']
 ['Mary' 20 'w']] 
3该数据类型为： <class 'numpy.ndarray'>


In [94]:
data = {'name':['Jack','Tom','Mary'],
        'age':[18,19,20],
       'gender':['m','m','w']}
frame = pd.DataFrame(data)
print(frame) 


   name  age gender
0  Jack   18      m
1   Tom   19      m
2  Mary   20      w


In [103]:

# Dataframe 创建方法一：由数组/list组成的字典
# 创建方法:pandas.Dataframe()
data1 = {'a':[1,2,3],
        'b':[3,4,5],
        'c':[5,6,7]}
data2 = {'one':np.random.rand(4),
        'two':np.random.rand(4)}   # 这里如果尝试  'two':np.random.rand(4) 会怎么样？
print(data1)
print(data2)
df1 = pd.DataFrame(data1,index=list("abc"))
df2 = pd.DataFrame(data2)
print(df1)
print(df2)
# 由数组/list组成的字典 创建Dataframe，columns为字典key列名，index为默认数字标签
# 字典的值的长度必须保持一致！


df1 = pd.DataFrame(data1, columns = ['b','c','a','d'])
print(df1)
df1 = pd.DataFrame(data1, columns = ['b','c'])
print(df1)
# columns参数：可以重新指定列的顺序，格式为list，如果现有数据中没有该列（比如'd'），则产生NaN值
# 如果columns重新指定时候，列的数量可以少于原数据

df2 = pd.DataFrame(data2, index = ['f1','f2','f3','f4',])  # 这里如果尝试  index = ['f1','f2','f3','f4'] 会怎么样？
print(df2)
# index参数：重新定义index，格式为list，长度必须保持一致

{'a': [1, 2, 3], 'b': [3, 4, 5], 'c': [5, 6, 7]}
{'one': array([0.81554889, 0.2255331 , 0.54954079, 0.04462295]), 'two': array([0.27128846, 0.71396163, 0.49744001, 0.07500131])}
   a  b  c
a  1  3  5
b  2  4  6
c  3  5  7
        one       two
0  0.815549  0.271288
1  0.225533  0.713962
2  0.549541  0.497440
3  0.044623  0.075001
   b  c  a    d
0  3  5  1  NaN
1  4  6  2  NaN
2  5  7  3  NaN
   b  c
0  3  5
1  4  6
2  5  7
         one       two
f1  0.815549  0.271288
f2  0.225533  0.713962
f3  0.549541  0.497440
f4  0.044623  0.075001


In [105]:
# Dataframe 创建方法二：由Series组成的字典

data1 = {'one':pd.Series(np.random.rand(2)),
        'two':pd.Series(np.random.rand(3))}  # 没有设置index的Series
data2 = {'one':pd.Series(np.random.rand(2), index = ['a','b']),
        'two':pd.Series(np.random.rand(3),index = ['a','b','c'])}  # 设置了index的Series
print(data1)
print(data2)
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2) 
print(df1)
print(df2)
# 由Seris组成的字典 创建Dataframe，columns为字典key，index为Series的标签（如果Series没有指定标签，则是默认数字标签）
# Series可以长度不一样，生成的Dataframe会出现NaN值

{'one': 0    0.684813
1    0.005400
dtype: float64, 'two': 0    0.844880
1    0.491651
2    0.623304
dtype: float64}
{'one': a    0.146764
b    0.114088
dtype: float64, 'two': a    0.725655
b    0.518237
c    0.137573
dtype: float64}
        one       two
0  0.684813  0.844880
1  0.005400  0.491651
2       NaN  0.623304
        one       two
a  0.146764  0.725655
b  0.114088  0.518237
c       NaN  0.137573


In [107]:
# Dataframe 创建方法三：通过二维数组直接创建

ar = np.random.rand(9).reshape(3,3)
print(ar)
df1 = pd.DataFrame(ar)
df2 = pd.DataFrame(ar, index = ['a', 'b', 'c'], columns = ['one','two','three'])  # 可以尝试一下index或columns长度不等于已有数组的情况
print(df1)
print(df2)
# 通过二维数组直接创建Dataframe，得到一样形状的结果数据，如果不指定index和columns，两者均返回默认数字格式
# index和colunms指定长度与原数组保持一致

[[0.02301452 0.64687344 0.62979082]
 [0.0246845  0.63184554 0.29981192]
 [0.07804763 0.11371532 0.88775054]]
          0         1         2
0  0.023015  0.646873  0.629791
1  0.024684  0.631846  0.299812
2  0.078048  0.113715  0.887751
        one       two     three
a  0.023015  0.646873  0.629791
b  0.024684  0.631846  0.299812
c  0.078048  0.113715  0.887751


In [109]:
# Dataframe 创建方法四：由字典组成的列表

data = [{'one': 1, 'two': 2}, {'one': 5, 'two': 10, 'three': 20}]#一个字典表示一行数据
print(data)
df1 = pd.DataFrame(data)
df2 = pd.DataFrame(data, index = ['a','b'])
df3 = pd.DataFrame(data, columns = ['one','two'])
print(df1)
print(df2)
print(df3)
# 由字典组成的列表创建Dataframe，columns为字典的key，index不做指定则为默认数组标签
# colunms和index参数分别重新指定相应列及行标签

[{'one': 1, 'two': 2}, {'one': 5, 'two': 10, 'three': 20}]
   one  three  two
0    1    NaN    2
1    5   20.0   10
   one  three  two
a    1    NaN    2
b    5   20.0   10
   one  two
0    1    2
1    5   10


In [115]:
# Dataframe 创建方法五：由字典组成的字典

data = {'Jack':{'math':90,'english':89,'art':78},
       'Marry':{'math':82,'english':95,'art':92},
       'Tom':{'math':78,'english':67}}
df1 = pd.DataFrame(data)
print(df1)
# 由字典组成的字典创建Dataframe，columns为字典的key，index为子字典的key

df2 = pd.DataFrame(data, columns = ['Jack','Tom', ])
#df3 = pd.DataFrame(data, index = ['a','b','c'])
print(df2)
print(df3)
# columns参数可以增加和减少现有列，如出现新的列，值为NaN
# index在这里和之前不同，并不能改变原有index，如果指向新的标签，值为NaN （非常重要！）

         Jack  Marry   Tom
art        78     92   NaN
english    89     95  67.0
math       90     82  78.0
         Jack   Tom
art        78   NaN
english    89  67.0
math       90  78.0
   one  two
0    1    2
1    5   10


In [143]:
#2.5作业
#方法一
data={'four':[4,5,6,7,8],'one':[1,2,3,4,5],'three':[3,4,5,6,7],'two':[2,3,4,5,6]}
df1=pd.DataFrame(data,index=list('abcde'))
print( "结果DataFrame为:")
print(df1)
print("----------------------------------")


#方法二
data={'four':pd.Series( (np.random.rand(5)*10),index=list('abcde')),
      'one':pd.Series( (np.random.rand(5)*10),index=list('abcde')),
      'three':pd.Series( (np.random.rand(5)*10),index=list('abcde')),
      'two':pd.Series( (np.random.rand(5)*10),index=list('abcde'))}
df1=pd.DataFrame(data )
print( "结果DataFrame为:")
print(df1)
print("----------------------------------")

#方法三
ar=np.random.rand(20).reshape(5,4)
print(ar) 
df=pd.DataFrame(ar,index=['a','b','c','d','e'],columns=['four','one','three','two'])
print( "结果DataFrame为:")
print(df)
print("----------------------------------")


#方法四,一个字典代表一行数字
data=[{'four':4,'one':1,'three':3,'two':2},
      {'four':5,'one':2,'three':4,'two':3},
      {'four':6,'one':3,'three':5,'two':4},
      {'four':7,'one':4,'three':6,'two':5},
      {'four':8,'one':5,'three':7,'two':6}]
df2=pd.DataFrame(data,index=list('abcde'))
print( "结果DataFrame为:")
print(df2)
print("----------------------------------")


#方法五
data={'four':{'a':4,'b':5,'c':6,'d':7,'e':8},
      'one':{'a':1,'b':2,'c':3,'d':4,'e':5}, 
     'three':{'a':3,'b':4,'c':5,'d':6,'e':7},
     'two':{'a':2,'b':3,'c':4,'d':5,'e':6},}
df1=pd.DataFrame(data )
print( "结果DataFrame为:")
print(df1)

结果DataFrame为:
   four  one  three  two
a     4    1      3    2
b     5    2      4    3
c     6    3      5    4
d     7    4      6    5
e     8    5      7    6
----------------------------------
结果DataFrame为:
       four       one     three       two
a  7.015020  3.376551  4.643156  1.050327
b  1.518165  4.304979  8.549739  9.267586
c  1.001636  7.801915  2.177595  5.590400
d  0.449556  7.953942  8.188833  2.774662
e  0.144016  3.621742  2.057197  7.543976
----------------------------------
[[0.19516036 0.00179036 0.27586572 0.45465015]
 [0.67072601 0.80387608 0.89638722 0.60886949]
 [0.56101325 0.16958678 0.83128167 0.99381545]
 [0.03090388 0.74328291 0.66012192 0.68868208]
 [0.78094325 0.67540705 0.2795564  0.79645537]]
结果DataFrame为:
       four       one     three       two
a  0.195160  0.001790  0.275866  0.454650
b  0.670726  0.803876  0.896387  0.608869
c  0.561013  0.169587  0.831282  0.993815
d  0.030904  0.743283  0.660122  0.688682
e  0.780943  0.675407  0.279556  0.79645

In [174]:
# 选择行与列

df = pd.DataFrame(np.random.rand(12).reshape(3,4)*100,
                   
                   columns = ['a','b','c','d'])
print(df)

data1 = df['a']
data2 = df[['a','c']]
data3=df[['b','c']]
 
print(data1,type(data1))
print(data2,type(data2))
print(data3)
 
print('-----')
# 按照列名选择列，只选择一列输出Series，选择多列输出Dataframe

data3 = df.loc[0]
 
print(data3,type(data3))
 
# 按照index选择行，只选择一行输出Series，选择多行输出Dataframe

           a          b          c          d
0  60.564589  61.271197  83.441124  63.280359
1  51.959530  97.863848  80.283811  95.148030
2  13.963416  55.820201   3.358034  27.122111
0    60.564589
1    51.959530
2    13.963416
Name: a, dtype: float64 <class 'pandas.core.series.Series'>
           a          c
0  60.564589  83.441124
1  51.959530  80.283811
2  13.963416   3.358034 <class 'pandas.core.frame.DataFrame'>
           b          c
0  61.271197  83.441124
1  97.863848  80.283811
2  55.820201   3.358034
-----
a    60.564589
b    61.271197
c    83.441124
d    63.280359
Name: 0, dtype: float64 <class 'pandas.core.series.Series'>


In [162]:
# df[] - 选择列
# 一般用于选择列，也可以选择行

df = pd.DataFrame(np.random.rand(12).reshape(3,4)*100,
                   index = ['one','two','three'],
                   columns = ['a','b','c','d'])
print(df)
print('-----')
data1 = df['a']
data2 = df[['b','c','d']]  # 尝试输入 data2 = df[['b','c','e']]
print(data1)
print(data2,type(data2))
# df[]默认选择列，[]中写列名（所以一般数据colunms都会单独制定，不会用默认数字列名，以免和index冲突）
# 单选列为Series，print结果为Series格式
# 多选列为Dataframe，print结果为Dataframe格式


data3=df[:2]#选择行0 .1
print(data3)
data4 = df[:1]
data5=df[1:2]
#data3 = df[0]
#data3 = df['one']
print(data3,type(data3))
print(data4,type(data4))
print(data5,type(data5))
# df[]中为数字时，默认选择行，且只能进行切片的选择，不能单独选择（df[0]）
# 输出结果为Dataframe，即便只选择一行
# df[]不能通过索引标签名来选择行(df['one'])

# 核心笔记：df[col]一般用于选择列，[]中写列名

               a          b          c          d
one    20.625538  19.856155  60.080409  29.822251
two     5.108611  71.218924  10.785991  75.982636
three  67.138474  19.928302   7.694516  83.882249
-----
one      20.625538
two       5.108611
three    67.138474
Name: a, dtype: float64
               b          c          d
one    19.856155  60.080409  29.822251
two    71.218924  10.785991  75.982636
three  19.928302   7.694516  83.882249 <class 'pandas.core.frame.DataFrame'>
             a          b          c          d
one  20.625538  19.856155  60.080409  29.822251
two   5.108611  71.218924  10.785991  75.982636
             a          b          c          d
one  20.625538  19.856155  60.080409  29.822251
two   5.108611  71.218924  10.785991  75.982636 <class 'pandas.core.frame.DataFrame'>
             a          b          c          d
one  20.625538  19.856155  60.080409  29.822251 <class 'pandas.core.frame.DataFrame'>
            a          b          c          d
two  5.10861

In [179]:
# df.loc[] - 按index选择行

df1 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   index = ['one','two','three','four'],
                   columns = ['a','b','c','d'])
df2 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   columns = ['a','b','c','d'])
print(df1)
print(df2)
print('-----')

data1 = df1.loc['three']
data2 = df2.loc[[3,2,1]]
print(data1)
print(data2)
print('------------------------------')
data1 = df1.loc['one']
data2 = df2.loc[1]
print(data1)
print(data2)
print('单标签索引\n-----')
# 单个标签索引，返回Series 

print('------------------------------')
data3 = df1.loc[['two','three','five']]
data4 = df2.loc[[3,2,1]]
print(data3)
print(data4)
print('多标签索引\n-----')
# 多个标签索引，如果标签不存在，则返回NaN
# 顺序可变


print('------------------------------')
data5 = df1.loc['one':'three']
 
data6 = df2.loc[1:3]
print(data5)
print(data6)
 
print('------------------------------')
 
print('切片索引')
# 可以做切片对象
# 末端包含

# 核心笔记：df.loc[label]主要针对index选择行，同时支持指定index，及默认数字index

               a          b          c          d
one    15.785452  74.264069  49.010922  76.710663
two    51.764924   4.337694  84.814248  76.346184
three   9.246252   7.673366  83.067893  66.041673
four   23.118123  74.268332  18.985181  65.371089
           a          b          c          d
0  91.238761  90.102306  65.128133  76.068692
1  40.055945  89.280095  54.773634  87.570403
2  12.176644  43.930320  37.769705  96.671902
3  48.137353  11.385919  51.800063  37.609334
-----
a     9.246252
b     7.673366
c    83.067893
d    66.041673
Name: three, dtype: float64
           a          b          c          d
3  48.137353  11.385919  51.800063  37.609334
2  12.176644  43.930320  37.769705  96.671902
1  40.055945  89.280095  54.773634  87.570403
------------------------------
a    15.785452
b    74.264069
c    49.010922
d    76.710663
Name: one, dtype: float64
a    40.055945
b    89.280095
c    54.773634
d    87.570403
Name: 1, dtype: float64
单标签索引
-----
-----------------------------

D:\ANA\lib\site-packages\ipykernel_launcher.py:25: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike


In [181]:
# df.iloc[] - 按照整数位置（从轴的0到length-1）选择行
# 类似list的索引，其顺序就是dataframe的整数位置，从0开始计

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   index = ['one','two','three','four'],
                   columns = ['a','b','c','d'])
print(df)
print('------')

print(df.iloc[0])
print(df.iloc[-1])
#print(df.iloc[4])
print('单位置索引\n-----')
# 单位置索引
# 和loc索引不同，不能索引超出数据行数的整数位置

print(df.iloc[[0,2]])
print(df.iloc[[3,2,1]])
print('多位置索引\n-----')
# 多位置索引
# 顺序可变

print(df.iloc[1:3])
print(df.iloc[::2])
print('切片索引')
# 切片索引和list类似
# 末端不包含
 

               a          b          c          d
one    60.495357  76.374280  93.706024   1.088187
two    99.823944  61.262178  89.062014  20.389827
three  67.338613  34.793916   5.381340  51.612198
four   44.020266  51.018470  79.526176  21.228311
------
a    60.495357
b    76.374280
c    93.706024
d     1.088187
Name: one, dtype: float64
a    44.020266
b    51.018470
c    79.526176
d    21.228311
Name: four, dtype: float64
单位置索引
-----
               a          b          c          d
one    60.495357  76.374280  93.706024   1.088187
three  67.338613  34.793916   5.381340  51.612198
               a          b          c          d
four   44.020266  51.018470  79.526176  21.228311
three  67.338613  34.793916   5.381340  51.612198
two    99.823944  61.262178  89.062014  20.389827
多位置索引
-----
               a          b          c          d
two    99.823944  61.262178  89.062014  20.389827
three  67.338613  34.793916   5.381340  51.612198
               a          b          c        

In [184]:
# 布尔型索引
# 和Series原理相同

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   index = ['one','two','three','four'],
                   columns = ['a','b','c','d'])
print(df)
print('------')

b1 = df < 20
print(b1,type(b1))
print(df[b1])  # 也可以书写为 df[df < 20]
print('------')
# 不做索引则会对数据每个值进行判断
# 索引结果保留 所有数据：True返回原数据，False返回值为NaN



b2 = df['a'] > 50
print(b2,type(b2))
print(df[b2])  # 也可以书写为 df[df['a'] > 50]
print('------')
# 单列做判断
# 索引结果保留 单列判断为True的行数据，包括其他列

b3 = df[['a','b']] > 50
print(b3,type(b3))
print(df[b3])  # 也可以书写为 df[df[['a','b']] > 50]
print('------')
# 多列做判断
# 索引结果保留 所有数据：True返回原数据，False返回值为NaN

b4 = df.loc[['one','three']] < 50
print(b4,type(b4))
print(df[b4])  # 也可以书写为 df[df.loc[['one','three']] < 50]
print('------')
# 多行做判断
# 索引结果保留 所有数据：True返回原数据，False返回值为NaN


               a          b          c          d
one    75.627366  78.298639  59.986395  64.389241
two    25.658058  95.175563  93.488743  77.191939
three   1.262521   0.811204   1.993315  82.406668
four   51.366625   9.850818  65.729447  97.170209
------
           a      b      c      d
one    False  False  False  False
two    False  False  False  False
three   True   True   True  False
four   False   True  False  False <class 'pandas.core.frame.DataFrame'>
              a         b         c   d
one         NaN       NaN       NaN NaN
two         NaN       NaN       NaN NaN
three  1.262521  0.811204  1.993315 NaN
four        NaN  9.850818       NaN NaN
------
one       True
two      False
three    False
four      True
Name: a, dtype: bool <class 'pandas.core.series.Series'>
              a          b          c          d
one   75.627366  78.298639  59.986395  64.389241
four  51.366625   9.850818  65.729447  97.170209
------
           a      b
one     True   True
two    False   Tr

In [189]:
# 多重索引：比如同时索引行和列
# 先选择列再选择行 —— 相当于对于一个数据，先筛选字段，再选择数据量

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   index = ['one','two','three','four'],
                   columns = ['a','b','c','d'])
print(df)
print('------')

print(df['a'].loc[['one','three']])
print('------')# 选择a列的one，three行
print(df[['b','c','d']].iloc[::2]) 
print('------')# 选择b，c，d列的one，three行
print(df[df['a'] < 50].iloc[:2])  
print('------')# 选择满足判断索引的前两行数据
print(df[df<50][['a','c','d']])
 

               a          b          c          d
one    63.547237  42.944568  93.443924  25.009886
two    60.651341  21.790149  98.932167  60.986251
three  27.491644  27.654891   8.447121  70.035529
four   69.784635  50.677180  44.866438  97.319755
------
one      63.547237
three    27.491644
Name: a, dtype: float64
------
               b          c          d
one    42.944568  93.443924  25.009886
three  27.654891   8.447121  70.035529
------
               a          b         c          d
three  27.491644  27.654891  8.447121  70.035529
------
               a          c          d
one          NaN        NaN  25.009886
two          NaN        NaN        NaN
three  27.491644   8.447121        NaN
four         NaN  44.866438        NaN


In [15]:
#2.6作业
import pandas as pd
import numpy as np
data = np.random.rand(16).reshape(4,4)*100
df = pd.DataFrame(data,index=['one','two','three','four'],columns=list('abcd'))
print(df)
print('------------------------')
print(df['b'])
print(df['c'])
print('------------------------')
 
print(df.loc[['three','four']]) #loc后面直接跟中括号
print(df.iloc[2:])#iloc后面直接跟中括号
print(df[2:4])
print('------------------------')
print(df.loc[['two','one']])
print('------------------------')
print(df[df>50])

               a          b          c          d
one    95.078089   7.473473   6.740715  55.264734
two    35.326574  53.039811   6.905752  78.127065
three  77.433325  20.219946  63.874482  55.731157
four   11.221190   6.126552  17.939495  98.457311
------------------------
one       7.473473
two      53.039811
three    20.219946
four      6.126552
Name: b, dtype: float64
one       6.740715
two       6.905752
three    63.874482
four     17.939495
Name: c, dtype: float64
------------------------
               a          b          c          d
three  77.433325  20.219946  63.874482  55.731157
four   11.221190   6.126552  17.939495  98.457311
               a          b          c          d
three  77.433325  20.219946  63.874482  55.731157
four   11.221190   6.126552  17.939495  98.457311
               a          b          c          d
three  77.433325  20.219946  63.874482  55.731157
four   11.221190   6.126552  17.939495  98.457311
------------------------
             a          b

In [17]:
# 数据查看、转置

df = pd.DataFrame(np.random.rand(16).reshape(8,2)*100,
                   columns = ['a','b'])
print(df.head(2))
print(df.tail())
# .head()查看头部数据
# .tail()查看尾部数据
# 默认查看5条

print(df.T)
# .T 转置

           a          b
0  68.488293  79.767017
1  64.997961  50.137184
           a          b
3  13.464268  14.071585
4  32.463359   5.667089
5  85.217839  50.232186
6  83.750588  15.178091
7  55.365801  38.318926
           0          1          2          3          4          5  \
a  68.488293  64.997961  82.380800  13.464268  32.463359  85.217839   
b  79.767017  50.137184  90.558155  14.071585   5.667089  50.232186   

           6          7  
a  83.750588  55.365801  
b  15.178091  38.318926  


In [19]:
# 添加与修改

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   columns = ['a','b','c','d'])
print(df)

df['e'] = 10
df.loc[4] = 20
print(df)
# 新增列/行并赋值

df['e'] = 20
df[['a','c']] = 100
print(df)
# 索引后直接修改值

           a          b          c          d
0  74.890466  98.675786  23.884218  44.612034
1  27.996384  53.025566  82.432879   4.229142
2  13.207633  55.813473  70.203938  63.947715
3  23.306929  81.973861  91.067278  68.268803
           a          b          c          d   e
0  74.890466  98.675786  23.884218  44.612034  10
1  27.996384  53.025566  82.432879   4.229142  10
2  13.207633  55.813473  70.203938  63.947715  10
3  23.306929  81.973861  91.067278  68.268803  10
4  20.000000  20.000000  20.000000  20.000000  20
     a          b    c          d   e
0  100  98.675786  100  44.612034  20
1  100  53.025566  100   4.229142  20
2  100  55.813473  100  63.947715  20
3  100  81.973861  100  68.268803  20
4  100  20.000000  100  20.000000  20


In [21]:
# 删除  del / drop()

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   columns = ['a','b','c','d'])
print(df)

del df['a']
print(df)
print('-----')
# del语句 - 删除列

print(df.drop(0))
print(df.drop([1,2]))
print(df)
print('-----')
# drop()删除行，inplace=False → 删除后生成新的数据，不改变原数据

print(df.drop(['d'], axis = 1))
print(df)
# drop()删除列，需要加上axis = 1，inplace=False → 删除后生成新的数据，不改变原数据

           a          b          c          d
0  54.318543  19.694286   0.004025  14.165997
1  51.625209   9.001720  81.922951  99.701571
2  52.754497  49.946729  79.518982  76.575559
3  79.879565  65.468421   2.035694   8.256730
           b          c          d
0  19.694286   0.004025  14.165997
1   9.001720  81.922951  99.701571
2  49.946729  79.518982  76.575559
3  65.468421   2.035694   8.256730
-----
           b          c          d
1   9.001720  81.922951  99.701571
2  49.946729  79.518982  76.575559
3  65.468421   2.035694   8.256730
           b         c          d
0  19.694286  0.004025  14.165997
3  65.468421  2.035694   8.256730
           b          c          d
0  19.694286   0.004025  14.165997
1   9.001720  81.922951  99.701571
2  49.946729  79.518982  76.575559
3  65.468421   2.035694   8.256730
-----
           b          c
0  19.694286   0.004025
1   9.001720  81.922951
2  49.946729  79.518982
3  65.468421   2.035694
           b          c          d
0  19.69428

In [25]:
# 对齐

df1 = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
df2 = pd.DataFrame(np.random.randn(7, 3), columns=['A', 'B', 'C'])
print(df1)
print('---------------------------')
print(df2)
print(df1 + df2)
# DataFrame对象之间的数据自动按照列和索引（行标签）对齐

          A         B         C         D
0  0.220583 -0.529018 -0.009401  1.347681
1 -0.608761  0.206216  1.679393 -0.342448
2  0.883304  1.207202 -0.388055 -0.744286
3  1.012657 -1.263674 -0.814384  0.094318
4  2.093061  0.595062  0.151527 -0.641532
5 -1.828598 -0.233240  1.780715  1.112567
6  1.187069  0.410391  0.749848  0.369541
7  2.019703 -1.923621  0.596268 -0.033682
8  0.468572  0.662383 -1.684686  0.318110
9  0.726289  0.689154  0.062895  0.461388
---------------------------
          A         B         C
0 -0.475002  0.178552 -1.495453
1  0.679735 -0.325063 -1.145626
2 -0.061009  2.031180  0.129315
3 -1.788327  0.655919 -0.017475
4  0.440158  0.959300  0.297370
5  0.648101  1.068527 -1.182431
6  0.829159  0.139834  0.273223
          A         B         C   D
0 -0.254419 -0.350467 -1.504854 NaN
1  0.070973 -0.118847  0.533767 NaN
2  0.822295  3.238382 -0.258739 NaN
3 -0.775670 -0.607755 -0.831859 NaN
4  2.533218  1.554362  0.448898 NaN
5 -1.180498  0.835287  0.598284 NaN
6 

In [27]:
# 排序1 - 按值排序 .sort_values
# 同样适用于Series

df1 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   columns = ['a','b','c','d'])
print(df1)
print(df1.sort_values(['a'], ascending = True))  # 升序
print(df1.sort_values(['a'], ascending = False))  # 降序
print('------')
# ascending参数：设置升序降序，默认升序
# 单列排序

df2 = pd.DataFrame({'a':[1,1,1,1,2,2,2,2],
                  'b':list(range(8)),
                  'c':list(range(8,0,-1))})
print(df2)
print(df2.sort_values(['a','c']))
# 多列排序，按列顺序排序

           a          b          c          d
0  80.010392   5.735909  15.088590  69.429627
1  42.714777  47.552930  63.739508  83.779987
2  19.250275  68.327180  88.596089  86.016348
3  16.350033  94.067943  80.742802  53.475781
           a          b          c          d
3  16.350033  94.067943  80.742802  53.475781
2  19.250275  68.327180  88.596089  86.016348
1  42.714777  47.552930  63.739508  83.779987
0  80.010392   5.735909  15.088590  69.429627
           a          b          c          d
0  80.010392   5.735909  15.088590  69.429627
1  42.714777  47.552930  63.739508  83.779987
2  19.250275  68.327180  88.596089  86.016348
3  16.350033  94.067943  80.742802  53.475781
------
   a  b  c
0  1  0  8
1  1  1  7
2  1  2  6
3  1  3  5
4  2  4  4
5  2  5  3
6  2  6  2
7  2  7  1
   a  b  c
3  1  3  5
2  1  2  6
1  1  1  7
0  1  0  8
7  2  7  1
6  2  6  2
5  2  5  3
4  2  4  4


In [29]:
# 排序2 - 索引排序 .sort_index

df1 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                  index = [5,4,3,2],
                   columns = ['a','b','c','d'])
df2 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                  index = ['h','s','x','g'],
                   columns = ['a','b','c','d'])
print(df1)
print(df1.sort_index())
print(df2)
print(df2.sort_index())
# 按照index排序
# 默认 ascending=True, inplace=False
print('--------------------------')

           a          b          c          d
5  41.702931  39.267596  98.177212  61.474081
4  29.793749  26.738144   2.454093  35.206585
3  12.943979  74.385254  32.692511  85.778620
2  77.245682  69.367717  79.517400  32.183794
           a          b          c          d
2  77.245682  69.367717  79.517400  32.183794
3  12.943979  74.385254  32.692511  85.778620
4  29.793749  26.738144   2.454093  35.206585
5  41.702931  39.267596  98.177212  61.474081
           a          b          c          d
h  69.249320  19.192481  28.764403  49.752709
s  73.577153  11.114785   1.186269  86.472836
x  31.521103  53.378071  82.617582  43.370587
g  45.907985  41.824064  38.193573  20.598660
           a          b          c          d
g  45.907985  41.824064  38.193573  20.598660
h  69.249320  19.192481  28.764403  49.752709
s  73.577153  11.114785   1.186269  86.472836
x  31.521103  53.378071  82.617582  43.370587


In [63]:
#2.7作业1
data=(np.random.rand(9)*100).reshape(3,3)
df=pd.DataFrame(data,index=list('abc'),columns=['v1','v2','v3'])
print("创建Dataframe为:\n",df)
print('-------------------------') 
print('按照index降序：\n',df.sort_index(ascending=False)) 
print('按照第二列值大小降序：\n',df.sort_values(['v2'],ascending=False))

创建Dataframe为:
           v1         v2         v3
a  32.352841  65.535583  24.078102
b   4.104510  92.087285  29.413682
c  73.435456  19.194605  75.692011
-------------------------
按照index降序：
           v1         v2         v3
c  73.435456  19.194605  75.692011
b   4.104510  92.087285  29.413682
a  32.352841  65.535583  24.078102
按照第二列值大小降序：
           v1         v2         v3
b   4.104510  92.087285  29.413682
a  32.352841  65.535583  24.078102
c  73.435456  19.194605  75.692011


In [64]:
#2.7作业2
data=(np.random.rand(10)*100).reshape(5,2)    
df1=pd.DataFrame(data,index=list('abcde'),columns=['v1','v2'])
print("创建Dataframe为:\n",df1)
df1.loc['b']=100 
df2=df1.drop(['e'])
print("修改后为:\n",df2.T)

创建Dataframe为:
           v1         v2
a  57.372718  75.163459
b  16.683738  86.630424
c  49.228968  40.497403
d   3.385719  59.508269
e  63.299248  96.935851
修改后为:
             a      b          c          d
v1  57.372718  100.0  49.228968   3.385719
v2  75.163459  100.0  40.497403  59.508269


In [65]:
df1 = pd.DataFrame(np.random.rand(5,2)*100,
                 index = ['a','b','c','d','e'],
                 columns = ['v1','v2'])
print('创建Dataframe为：\n',df1,'\n-------')
df2 = df1.T.drop('e',axis = 1)#删除列
df2['b'] = 100
print('修改后为：\n',df2,'\n-------')

创建Dataframe为：
           v1         v2
a  20.147949  71.821862
b  51.796702  72.474635
c  52.720179  10.716562
d  68.647102  24.483081
e  34.383808  40.836160 
-------
修改后为：
             a    b          c          d
v1  20.147949  100  52.720179  68.647102
v2  71.821862  100  10.716562  24.483081 
-------
